create table if not exists public.cheffing_pos_orders (
  pos_order_id text primary key,
  outlet_id text not null default 'default',
  outlet_name text,
  opened_at timestamp without time zone not null,
  closed_at timestamp without time zone,
  custom_order_id text,
  order_name text,
  opened_by text,
  closed_table text,
  clients integer,
  duration_seconds integer,
  status text,
  currency text,
  total_gross numeric,
  total_net numeric,
  total_vat numeric,
  total_payments numeric,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.cheffing_pos_order_items (
  id bigint generated by default as identity primary key,
  pos_order_id text not null,
  outlet_id text not null default 'default',
  outlet_name text,
  opened_at timestamp without time zone not null,
  closed_at timestamp without time zone,
  product_name text not null,
  sku text,
  gift_card_code text,
  quantity numeric not null,
  unit_price_gross numeric not null default 0,
  discount_gross numeric not null default 0,
  total_gross numeric not null default 0,
  total_net numeric,
  vat_amount numeric,
  currency text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.cheffing_pos_product_links (
  pos_product_id text primary key,
  dish_id uuid not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'cheffing_pos_order_items_pos_order_id_fkey'
      and conrelid = 'public.cheffing_pos_order_items'::regclass
  ) then
    alter table public.cheffing_pos_order_items
      add constraint cheffing_pos_order_items_pos_order_id_fkey
      foreign key (pos_order_id)
      references public.cheffing_pos_orders(pos_order_id)
      on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'cheffing_pos_product_links_dish_id_fkey'
      and conrelid = 'public.cheffing_pos_product_links'::regclass
  ) then
    alter table public.cheffing_pos_product_links
      add constraint cheffing_pos_product_links_dish_id_fkey
      foreign key (dish_id)
      references public.cheffing_dishes(id)
      on delete cascade;
  end if;
end
$$;

create index if not exists cheffing_pos_orders_opened_at_idx on public.cheffing_pos_orders(opened_at);
create index if not exists cheffing_pos_orders_outlet_idx on public.cheffing_pos_orders(outlet_id);
create index if not exists cheffing_pos_order_items_order_idx on public.cheffing_pos_order_items(pos_order_id);
create index if not exists cheffing_pos_order_items_opened_at_idx on public.cheffing_pos_order_items(opened_at);
create unique index if not exists cheffing_pos_order_items_dedupe_idx
  on public.cheffing_pos_order_items(pos_order_id, product_name, unit_price_gross, discount_gross);
create index if not exists cheffing_pos_product_links_dish_id_idx on public.cheffing_pos_product_links(dish_id);

create or replace function public.cheffing_pos_refresh_sales_daily(
  p_from date default null,
  p_to date default null
)
returns void
language plpgsql
as $$
begin
  insert into public.cheffing_pos_sales_daily (
    sale_day,
    outlet_id,
    pos_product_id,
    pos_product_name,
    units,
    revenue,
    source,
    created_at,
    updated_at
  )
  select
    oi.opened_at::date as sale_day,
    oi.outlet_id,
    (oi.outlet_id || ':' || oi.product_name) as pos_product_id,
    oi.product_name as pos_product_name,
    sum(oi.quantity)::numeric as units,
    sum(oi.total_gross)::numeric as revenue,
    'csv'::text as source,
    now(),
    now()
  from public.cheffing_pos_order_items oi
  where (p_from is null or oi.opened_at::date >= p_from)
    and (p_to is null or oi.opened_at::date <= p_to)
  group by 1,2,3,4
  on conflict (sale_day, outlet_id, pos_product_id)
  do update
    set pos_product_name = excluded.pos_product_name,
        units = excluded.units,
        revenue = excluded.revenue,
        source = excluded.source,
        updated_at = now();
end;
$$;

alter table public.cheffing_pos_orders enable row level security;
alter table public.cheffing_pos_order_items enable row level security;
alter table public.cheffing_pos_product_links enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cheffing_pos_orders' and policyname = 'cheffing_pos_orders_all'
  ) then
    create policy cheffing_pos_orders_all
      on public.cheffing_pos_orders
      using (public.cheffing_is_allowed())
      with check (public.cheffing_is_allowed());
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cheffing_pos_order_items' and policyname = 'cheffing_pos_order_items_all'
  ) then
    create policy cheffing_pos_order_items_all
      on public.cheffing_pos_order_items
      using (public.cheffing_is_allowed())
      with check (public.cheffing_is_allowed());
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cheffing_pos_product_links' and policyname = 'cheffing_pos_product_links_select'
  ) then
    create policy cheffing_pos_product_links_select
      on public.cheffing_pos_product_links
      for select
      using (public.cheffing_is_allowed());
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cheffing_pos_product_links' and policyname = 'cheffing_pos_product_links_write'
  ) then
    create policy cheffing_pos_product_links_write
      on public.cheffing_pos_product_links
      using (public.cheffing_is_admin())
      with check (public.cheffing_is_admin());
  end if;
end
$$;
